// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJbzdqaZVSEPDIYvD5StL-6sJG0LvjFc',
    appId: '1:268520308199:web:82763ab2aab62105171142',
    messagingSenderId: '268520308199',
    projectId: 'saveflow-84a30',
    authDomain: 'saveflow-84a30.firebaseapp.com',
    storageBucket: 'saveflow-84a30.firebasestorage.app',
    measurementId: 'G-VWW24VNTMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWz4awCqvvssAV8XMRJ0ZkxV3uz7LP4Eo',
    appId: '1:268520308199:android:4375a6868f4c6281171142',
    messagingSenderId: '268520308199',
    projectId: 'saveflow-84a30',
    storageBucket: 'saveflow-84a30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSpirLIiNubK-P7czzpA0GayxK-x8RepE',
    appId: '1:268520308199:ios:fa93a31f39a8382d171142',
    messagingSenderId: '268520308199',
    projectId: 'saveflow-84a30',
    storageBucket: 'saveflow-84a30.firebasestorage.app',
    iosBundleId: 'com.example.saveFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAJbzdqaZVSEPDIYvD5StL-6sJG0LvjFc',
    appId: '1:268520308199:web:c202a0531a008046171142',
    messagingSenderId: '268520308199',
    projectId: 'saveflow-84a30',
    authDomain: 'saveflow-84a30.firebaseapp.com',
    storageBucket: 'saveflow-84a30.firebasestorage.app',
    measurementId: 'G-6L3PH5BL8F',
  );
}
